name: witthuhn2021
channels:
  - defaults
dependencies:
  - netcdf4
  - xarray
  - rpy2
  - cartopy
  - jupyterlab
  - pyproj
  - matplotlib
  - pandas
  - xlsxwriter
  - jupyter
  - scipy
  - dask
  - numpy
  - h5py
  - pip
  - pip:
    - SkillMetrics
    - jstyleson
    - clear_sky_detection @ git+https://github.com/jonas-witthuhn/clear_sky_detection.git#egg=clear_sky_detection
    - clear_sky_models @ git+https://github.com/jonas-witthuhn/clear-sky-models.git#egg=clear_sky_models
    - ecrad_python @ git+https://github.com/jonas-witthuhn/ecrad_python.git#egg=ecrad_python
    - CAMS_aerosol_props @ git+https://github.com/jonas-witthuhn/CAMS_aerosol_props.git#egg=CAMS_aerosol_props




